### ISSUE TITLE
example in the README

### ISSUE THREAD

**Issue by jabbalaci** [mraza007/videodownloader#2]
Can you add an example in the README on how to use the script? That would be useful.

**Comment by mraza007** [comment]
I will do that :+1:

**Comment by mraza007** [comment]
Added the demo

**Comment by jabbalaci** [comment]
It's not visible at all in the README. What you could do is add a screenshot of the video, and when the user clicks on it, redirect him/her to Vimeo. It's a trick since videos can't be embedded in markdown (or at least I didn't find a way). I have done the same thing here: https://github.com/jabbalaci/JiVE-Image-Viewer

**Comment by mraza007** [comment]
Done :+1:  Thanks alot for the tip
