### ISSUE TITLE
Would it be better to use the video ID vs the full URL?

### ISSUE THREAD

**Issue by jslay88** [mraza007/videodownloader#4]
Take URL `https://www.youtube.com/watch?v=rfscVS0vtbw` for example.

All (as far as I know) YouTube videos are ID and accessible with the `watch?v=videoID`. Would it not be better to pass the video ID?, or at least, auto detect if its the URL or ID?

```
if 'youtube` not in url:
    url = 'https://www.youtube.com/watch?v=%s' % url
```

or maybe even just look for `https` in case its one of the YouTube shortened links?

**Comment by mraza007** [comment]
I think full url is better

**Comment by jslay88** [comment]
I added support for both in that PR. Can pass url or id, it will detect non url and wrap it into a url. Url is url if contains https
