### ISSUE TITLE
Windows EXE

### ISSUE THREAD

**Issue by jslay88** [mraza007/videodownloader#9]
We should leave the EXE out of the repo, and only add it to 'releases'.

I haven't done much in the way of using the exe compilers, but I can mess around with them tomorrow or later this week.

**Comment by mraza007** [comment]
Gotchaya Lets do that I even created one using pyinstaller I am about to test it on a windows machine at my school

**Comment by mraza007** [comment]
Hey by the way you can create slack if you for better communication. I am adding you as a contributor to this repo

**Comment by mraza007** [comment]
sent you an invite

**Comment by mraza007** [comment]
Should we create a gitter channel / slack or discord for communication

**Comment by jslay88** [comment]
I have created a Release, and added the binary to it. It appears to be working well. 

I primarily use Discord, but also have Slack. Either work.

**Comment by mraza007** [comment]
Gotchaya I'll setup slack will send you invite
